# -*- coding: utf-8 -*-
"""Introducción a Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3vA1rw7hXzjcse0N-4uEd_QQurExq8l

# Pandas
"""

import pandas as pd

"""Crear un data frame es muy parecido a crear un diccionario"""

df = pd.DataFrame({
    "Carnet": [123, 456, 789, 987, 654],
    "Hoja de trabajo 1": [80, 85, 75, 40, 100],
    "Hoja de trabajo 2": [90, 90, 75, 61, 100],
    "Hoja de trabajo 3": [80, 80, 0, 50, 85],
})

"""Imprimir un data muestra de forma ordenada la información."""

print(df)

"""Tabmbién es posible ver la información en formato tabla pero esto solo es posible en Jupyter Notebooks"""

print(df)

"""## Instrucciones básicas

La forma del data frame nos da información sobre la cantidad de imformación que este tiene
"""

print(df.shape)

"""Si se requiere estadistica básica es posible utilizar la función describe"""

print(df.describe())

"""Es posible sacar estadística de forma más específica:"""

print(df.mean())

print(df.count())

print(df.max())

print(df.min())

print(df.std())

print(df["Hoja de trabajo 1"])

print(df["Hoja de trabajo 1"].mean())

"""También es posible generar sub data frames con ciertas columnas"""

df2 = df[["Hoja de trabajo 1", "Hoja de trabajo 3"]]

print(df2)

print(df2.shape)

"""Si se requiere obtener un valor específico es posible hacerlo:"""

valor = df["Hoja de trabajo 1"][0]

print(valor)

"""## Busqueda de información

Poder acceder a información específica es uno de los poderes más grandes de Pandas. Para lograr esto se puede utilizar LOC ya que permite acceder a un grupo de filas y columnas usando etiquetas.
"""

# OJO sin print la información de muestra en una tabla
# esto SOLO pasa en los jupyter notebooks

df.loc[df["Hoja de trabajo 1"] >= 61]

"""También es posible filtar la información en el dataframe para limitar el resultado."""

distinguidos = df.loc[df["Hoja de trabajo 1"] > 80]

print(distinguidos)

print("\n--\n")

print(distinguidos[["Carnet", "Hoja de trabajo 1"]])

