# -*- coding: utf-8 -*-
"""Pokemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCIE59ZeHKWsvXbGc0_RKfTbmI4Aw7Kd

# Pokemon
"""

import pandas as pd

"""Abrir el csv con datos del pokemon"""

pokemon = pd.read_csv('pokemon.csv')

print(pokemon)

poderosos = pokemon.loc[pokemon["Attack"] >= 100]

print(poderosos)

mitad = pokemon.loc[pokemon["#"] < 400]

print(mitad)

legendarios_hielo = pokemon.loc[(pokemon["Legendary"] == True) & (pokemon["Type 1"] == "Ice")]

print(legendarios_hielo[["#", "Name", "Type 1", "Type 2", "Attack", "Defense"]])

dos_a_cuatro = pokemon.loc[(pokemon["#"] >= 200) & (pokemon["#"] <= 400)]

print(dos_a_cuatro)

poderosos_legendarios = pokemon.loc[(pokemon["Attack"] >= 100) & (pokemon["Legendary"] == True)]

print(poderosos_legendarios["Name"])

"""Es posible usar la función query para hacer más "natural" la búsqueda"""

poderosos_fantasmas = pokemon.query("Attack >= 10 and (Type_1 == 'Ghost' or Type_1 == 'Poison')")

print(poderosos_fantasmas)

"""Se pueden utilizar ciclos para recorrer la información"""

for i in range(len(pokemon)):
    if (pokemon.loc[i]["Legendary"] and pokemon.loc[i]["Type 1"] == "Fire"):
        print(pokemon.loc[i]["Name"] + " - " + str(pokemon.loc[i]["Attack"]) + "/" + str(pokemon.loc[i]["Defense"]))